### ISSUE TITLE
Missing Modules for your ADExportImport

### ISSUE THREAD

**Issue by StachStach** [jaols/PSJumpStart#1]
I installed your PSJumpStart package but it has several missing scripts or function, at least in the current v1.3.0, that are needed by your ADExportImport project. I searched the entire hard drive for the missing modules and found nothing. Here are the errors...*

Please release a new version that contains the missing modules or point me to a fix please as I need this for our lab.

INFORMATION;10/2/2024 5:57:35 PM;Start Execution
Get-ReplaceStrings: E:\Powershell\ADExportImport\Export-AdUsers.ps1:123
Line |
 123 |  $ReplaceStrings=Get-ReplaceStrings $Replacements
     |                  ~~~~~~~~~~~~~~~~~~
     | The term 'Get-ReplaceStrings' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
     | again.
Get-StandardExludeAttributes: E:\Powershell\ADExportImport\Export-AdUsers.ps1:125
Line |
 125 |  $ExportExcludeAttributes+=Get-StandardExludeAttributes -Export
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-StandardExludeAttributes' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
INFORMATION;10/2/2024 5:57:35 PM;Save data to E:\Powershell\ADExportImport\.Users.2024-10-02.json
ConvertTo-GenericStrings: E:\Powershell\ADExportImport\Export-AdUsers.ps1:164
Line |
 164 |      $ObjectList.ToString() | ConvertTo-GenericStrings -ReplaceStrings …
     |                               ~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'ConvertTo-GenericStrings' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
INFORMATION;10/2/2024 5:57:35 PM;End Execution

**Comment by StachStach** [comment]
I finally noticed the locallib folder at the top of the file list in Github, so once I openened the folder and downloaded the ps1 files into my locallib folder, the scripts started working without errors. :)

I hope that this little tip helps someone else along the way.

**Comment by jaols** [comment]
Yes. The PSJumpStart module will load any function files living in the locallib subfolder at the script file location. The last version of PSJumpStart will even load DLLs living in any locallib folder.
